doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'

        types:
          genre_id:
            class: RaspinuOffice\Backoffice\Products\Genre\Infrastructure\Persistence\Doctrine\Type\GenreIdType
          genre_name:
            class: RaspinuOffice\Backoffice\Products\Genre\Infrastructure\Persistence\Doctrine\Type\GenreNameType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            genre:
              mapping: true
              type: yml
              dir: '%kernel.project_dir%/src/Backoffice/Products/Genre/Infrastructure/Persistence/Doctrine/Mapping'
              prefix: 'RaspinuOffice\Backoffice\Products\Genre\Domain'
              alias: genre
