doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver: pdo_mysql
                url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'

        types:
            genre_id:
              class: RaspinuOffice\Backoffice\Products\Genre\Infrastructure\Persistence\Doctrine\Type\GenreIdType
            genre_name:
              class: RaspinuOffice\Backoffice\Products\Genre\Infrastructure\Persistence\Doctrine\Type\GenreNameType

            label_id:
              class: RaspinuOffice\Backoffice\Products\Label\Infrastructure\Persistence\Doctrine\Type\LabelIdType
            label_name:
              class: RaspinuOffice\Backoffice\Products\Label\Infrastructure\Persistence\Doctrine\Type\LabelNameType

            supplier_id:
              class: RaspinuOffice\Backoffice\Products\Supplier\Infrastructure\Persistence\Doctrine\Type\SupplierIdType
            supplier_name:
              class: RaspinuOffice\Backoffice\Products\Supplier\Infrastructure\Persistence\Doctrine\Type\SupplierNameType

            style_id:
              class: RaspinuOffice\Backoffice\Products\Style\Infrastructure\Persistence\Doctrine\Type\StyleIdType
            style_name:
              class: RaspinuOffice\Backoffice\Products\Style\Infrastructure\Persistence\Doctrine\Type\StyleNameType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            genre:
              mapping: true
              type: yml
              dir: '%kernel.project_dir%/src/Backoffice/Products/Genre/Infrastructure/Persistence/Doctrine/Mapping'
              prefix: 'RaspinuOffice\Backoffice\Products\Genre\Domain'
              alias: genre

            label:
              mapping: true
              type: yml
              dir: '%kernel.project_dir%/src/Backoffice/Products/Label/Infrastructure/Persistence/Doctrine/Mapping'
              prefix: 'RaspinuOffice\Backoffice\Products\Label\Domain'
              alias: label

            supplier:
              mapping: true
              type: yml
              dir: '%kernel.project_dir%/src/Backoffice/Products/Supplier/Infrastructure/Persistence/Doctrine/Mapping'
              prefix: 'RaspinuOffice\Backoffice\Products\Supplier\Domain'
              alias: supplier

            style:
              mapping: true
              type: yml
              dir: '%kernel.project_dir%/src/Backoffice/Products/Style/Infrastructure/Persistence/Doctrine/Mapping'
              prefix: 'RaspinuOffice\Backoffice\Products\Style\Domain'
              alias: style