version:  '3'
services:
    mysql:
        image: mariadb
        command: ["--default-authentication-plugin=mysql_native_password"]
        restart: on-failure
        volumes:
            - $PWD/data:/var/lib/mysql
        ports:
            - "3308:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: dddedu
        container_name: dddedu_mysql
    nginx:
        image: nginx:alpine
        restart: on-failure
        environment:
            APP_ENV: dev
        depends_on:
            - php
        volumes:
            - '.:/var/www/html'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
        ports:
            - "8080:80"
            - "443:443"
        container_name: dddedu_nginx
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        restart: on-failure
        volumes:
            - '.:/var/www/html'
        env_file:
            - .env
        user: www-data:www-data
        container_name: dddedu_php
